const MEDIUM_QUESTION_IDS = new Set([
  'binary-two',
  'url-address',
  'table-rows',
  'git-version',
  'prompt-ai',
  'phishing-fake',
])

const HARD_QUESTION_IDS = new Set([
  'javascript-web',
  'sql-structured',
  'chatgpt-company',
  'claude-company',
])

const quizData = [
  {
    id: 'computer-program',
    template: 'A computer follows a set of instructions called a ____.',
    answer: 'program',
    acceptableAnswers: ['program'],
    category: 'CS Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Computer science word' },
      { label: 'Nudge', text: 'Software is made of many of these.' },
    ],
    fact: 'A program is a set of instructions that tells a computer what to do.',
  },
  {
    id: 'hardware-physical',
    template: 'The physical parts of a computer are called ____.',
    answer: 'hardware',
    acceptableAnswers: ['hardware'],
    category: 'CS Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Computer term' },
      { label: 'Nudge', text: 'Keyboard, monitor, and mouse are part of it.' },
    ],
    fact: 'Hardware means the physical devices and components of a computer system.',
  },
  {
    id: 'software-programs',
    template: 'Apps and programs together are called ____.',
    answer: 'software',
    acceptableAnswers: ['software'],
    category: 'CS Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Computer term' },
      { label: 'Nudge', text: 'It is the opposite of hardware.' },
    ],
    fact: 'Software includes the applications and system programs that run on hardware.',
  },
  {
    id: 'cpu-brain',
    template: 'The CPU is often called the ____ of the computer.',
    answer: 'brain',
    acceptableAnswers: ['brain'],
    category: 'CS Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Body part' },
      { label: 'Nudge', text: 'It controls and processes instructions.' },
    ],
    fact: 'The CPU handles processing and control, so people often call it the brain of the computer.',
  },
  {
    id: 'binary-two',
    template: 'Binary uses only two digits: 0 and ____.',
    answer: '1',
    acceptableAnswers: ['1'],
    category: 'CS Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'A single digit' },
      { label: 'Nudge', text: 'It comes after zero.' },
    ],
    fact: 'Binary is the base-2 number system used by computers.',
  },
  {
    id: 'internet-network',
    template: 'The internet is a global network of ____.',
    answer: 'computers',
    acceptableAnswers: ['computers'],
    category: 'Networking',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Plural noun' },
      { label: 'Nudge', text: 'Devices connect together to share information.' },
    ],
    fact: 'The internet connects millions of computers and devices across the world.',
  },
  {
    id: 'html-language',
    template: 'HTML stands for HyperText Markup ____.',
    answer: 'language',
    acceptableAnswers: ['language'],
    category: 'Web Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Web term' },
      { label: 'Nudge', text: 'It is the last word in the full form of HTML.' },
    ],
    fact: 'HTML gives structure to a web page.',
  },
  {
    id: 'css-sheets',
    template: 'CSS stands for Cascading Style ____.',
    answer: 'sheets',
    acceptableAnswers: ['sheets'],
    category: 'Web Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Plural word' },
      { label: 'Nudge', text: 'CSS controls colors, spacing, and layout.' },
    ],
    fact: 'CSS is used to style web pages.',
  },
  {
    id: 'javascript-web',
    template: 'JavaScript is mainly used to make web pages more ____.',
    answer: 'interactive',
    acceptableAnswers: ['interactive'],
    category: 'Web Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Adjective' },
      { label: 'Nudge', text: 'Buttons, forms, and animations often need this.' },
    ],
    fact: 'JavaScript adds behavior and interactivity to websites.',
  },
  {
    id: 'url-address',
    template: 'A website address on the internet is called a ____.',
    answer: 'url',
    acceptableAnswers: ['url'],
    category: 'Web Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Short web term' },
      { label: 'Nudge', text: 'You type it in the browser bar.' },
    ],
    fact: 'A URL tells the browser where to find a resource on the web.',
  },
  {
    id: 'database-data',
    template: 'A database is used to store and organize ____.',
    answer: 'data',
    acceptableAnswers: ['data'],
    category: 'Data Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Information word' },
      { label: 'Nudge', text: 'Apps save user records and scores as this.' },
    ],
    fact: 'Databases help applications store and retrieve data efficiently.',
  },
  {
    id: 'sql-structured',
    template: 'SQL is commonly used to work with ____.',
    answer: 'databases',
    acceptableAnswers: ['databases', 'database'],
    category: 'Data Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Storage systems' },
      { label: 'Nudge', text: 'Tables, rows, and queries belong here.' },
    ],
    fact: 'SQL helps create, read, update, and delete data in relational databases.',
  },
  {
    id: 'table-rows',
    template: 'In a database table, information is stored in rows and ____.',
    answer: 'columns',
    acceptableAnswers: ['columns'],
    category: 'Data Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Table word' },
      { label: 'Nudge', text: 'They go vertically in a table.' },
    ],
    fact: 'Database tables are organized using rows and columns.',
  },
  {
    id: 'excel-spreadsheet',
    template: 'Microsoft Excel is mainly used as a ____.',
    answer: 'spreadsheet',
    acceptableAnswers: ['spreadsheet'],
    category: 'Data Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Office software type' },
      { label: 'Nudge', text: 'People use it for tables, formulas, and charts.' },
    ],
    fact: 'Excel is a spreadsheet tool used for calculations, analysis, and data organization.',
  },
  {
    id: 'python-language',
    template: 'Python is a programming ____.',
    answer: 'language',
    acceptableAnswers: ['language'],
    category: 'Programming',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Technical word' },
      { label: 'Nudge', text: 'Java and C are also examples of one.' },
    ],
    fact: 'Python is a popular programming language used in web, automation, data, and AI work.',
  },
  {
    id: 'bug-error',
    template: 'A mistake in code is commonly called a ____.',
    answer: 'bug',
    acceptableAnswers: ['bug'],
    category: 'Programming',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Coding word' },
      { label: 'Nudge', text: 'Developers fix these during debugging.' },
    ],
    fact: 'A bug is an error or flaw in software.',
  },
  {
    id: 'debugging-fixing',
    template: 'Finding and fixing errors in code is called ____.',
    answer: 'debugging',
    acceptableAnswers: ['debugging'],
    category: 'Programming',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Developer activity' },
      { label: 'Nudge', text: 'You do it after you discover a bug.' },
    ],
    fact: 'Debugging is the process of identifying and fixing issues in software.',
  },
  {
    id: 'git-version',
    template: 'Git is a tool used for version ____.',
    answer: 'control',
    acceptableAnswers: ['control'],
    category: 'Programming',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Software practice' },
      { label: 'Nudge', text: 'It helps track file changes.' },
    ],
    fact: 'Version control helps teams manage code changes safely.',
  },
  {
    id: 'github-code',
    template: 'GitHub is mainly used to host and share ____.',
    answer: 'code',
    acceptableAnswers: ['code'],
    category: 'Programming',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'What developers write' },
      { label: 'Nudge', text: 'Repositories usually contain this.' },
    ],
    fact: 'GitHub is a platform for storing and collaborating on code repositories.',
  },
  {
    id: 'ai-artificial',
    template: 'AI stands for Artificial ____.',
    answer: 'intelligence',
    acceptableAnswers: ['intelligence'],
    category: 'AI Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'AI full form word' },
      { label: 'Nudge', text: 'It relates to smart decision-making by machines.' },
    ],
    fact: 'AI means Artificial Intelligence.',
  },
  {
    id: 'ml-machine',
    template: 'ML stands for Machine ____.',
    answer: 'learning',
    acceptableAnswers: ['learning'],
    category: 'AI Basics',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'AI full form word' },
      { label: 'Nudge', text: 'Models improve by studying data in this field.' },
    ],
    fact: 'Machine learning is a branch of AI that learns patterns from data.',
  },
  {
    id: 'chatgpt-company',
    template: 'ChatGPT was created by ____.',
    answer: 'openai',
    acceptableAnswers: ['openai'],
    category: 'AI Tools',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Company name' },
      { label: 'Nudge', text: 'It also makes GPT models.' },
    ],
    fact: 'ChatGPT is an AI assistant created by OpenAI.',
  },
  {
    id: 'claude-company',
    template: 'Claude is an AI assistant made by ____.',
    answer: 'anthropic',
    acceptableAnswers: ['anthropic'],
    category: 'AI Tools',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Company name' },
      { label: 'Nudge', text: 'It is known for building Claude models.' },
    ],
    fact: 'Claude is an AI assistant developed by Anthropic.',
  },
  {
    id: 'prompt-ai',
    template: 'A question or instruction given to an AI tool is called a ____.',
    answer: 'prompt',
    acceptableAnswers: ['prompt'],
    category: 'AI Tools',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'AI term' },
      { label: 'Nudge', text: 'Better wording usually gives better output.' },
    ],
    fact: 'A prompt tells an AI system what task to perform.',
  },
  {
    id: 'chatbot-conversation',
    template: 'ChatGPT and Claude are examples of AI ____.',
    answer: 'chatbots',
    acceptableAnswers: ['chatbots', 'chatbot'],
    category: 'AI Tools',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Plural noun' },
      { label: 'Nudge', text: 'They can answer questions in conversation form.' },
    ],
    fact: 'AI chatbots can respond to users in natural language conversations.',
  },
  {
    id: 'password-secret',
    template: 'A strong ____ helps protect your online account.',
    answer: 'password',
    acceptableAnswers: ['password'],
    category: 'Cyber Safety',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Account secret' },
      { label: 'Nudge', text: 'It should be unique and hard to guess.' },
    ],
    fact: 'Strong passwords reduce the chance of account compromise.',
  },
  {
    id: 'phishing-fake',
    template: 'A fake email sent to steal your login details is called ____.',
    answer: 'phishing',
    acceptableAnswers: ['phishing'],
    category: 'Cyber Safety',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Cyber attack' },
      { label: 'Nudge', text: 'It often pretends to come from a trusted source.' },
    ],
    fact: 'Phishing attacks try to trick people into sharing passwords or personal information.',
  },
  {
    id: 'infosys-company',
    template: 'The company behind this virtual internship is ____.',
    answer: 'infosys',
    acceptableAnswers: ['infosys'],
    category: 'Infosys',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Company name' },
      { label: 'Nudge', text: 'It starts with the letters I-N-F-O.' },
    ],
    fact: 'Infosys is a major technology company known for digital services, consulting, and learning programs.',
  },
  {
    id: 'resume-job',
    template: 'A document that summarizes your skills and education is a ____.',
    answer: 'resume',
    acceptableAnswers: ['resume', 'cv'],
    category: 'Student Skills',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Career document' },
      { label: 'Nudge', text: 'Students share it while applying for internships.' },
    ],
    fact: 'A resume presents your education, skills, projects, and experience in a short format.',
  },
  {
    id: 'teamwork-collaboration',
    template: 'Working well with others in a project is called ____.',
    answer: 'teamwork',
    acceptableAnswers: ['teamwork'],
    category: 'Student Skills',
    difficulty: 'easy',
    timeLimit: 16,
    hints: [
      { label: 'Thing', text: 'Soft skill' },
      { label: 'Nudge', text: 'It matters when multiple people build one project.' },
    ],
    fact: 'Teamwork helps students and professionals complete tasks more effectively together.',
  },
]

module.exports = quizData.map((question) => ({
  ...question,
  timeLimit: 20,
  difficulty: HARD_QUESTION_IDS.has(question.id)
    ? 'hard'
    : MEDIUM_QUESTION_IDS.has(question.id)
      ? 'medium'
      : 'easy',
}))
